// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mffdhuihiyosckriivfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZmRodWloaXlvc2NrcmlpdmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NTI0NjUsImV4cCI6MjA3ODMyODQ2NX0.imWa1Shl84ObzFdmD7QvEjREAuo8aUOpfZzA1BF_2x4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);